# running simulations to test MCpbt and scobi_deux
## sample rate with the small scenario

#install if haven't already
# devtools::install_github("delomast/fishCompTools")
# devtools::install_github("delomast/devMCpbt")

#load libraries
if(Sys.info()["sysname"] == "Windows"){
	#for desktop
	library(fishCompTools)
	library(devMCpbt)
} else {
	#for server
	library(fishCompTools, lib.loc = "../../Rlib/")
	library(devMCpbt, lib.loc = "../../Rlib/")
}


# first, load in the base scenario inputs

# relative sizes of the wild groups
gsiComp <- read.table("./inputs/smallScenario/gsiCompIn.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# relative sizes of the unclipped hatchery groups
pbtComp <- read.table("./inputs/smallScenario/pbtCompIn.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# gsi assignmnet of the unclipped hatchery groups
gsiOfPbt <- read.table("./inputs/smallScenario/gsiOfPbtIn.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
# normalize
for(i in 1:nrow(gsiOfPbt)){
	gsiOfPbt[i,2:ncol(gsiOfPbt)] <- gsiOfPbt[i,2:ncol(gsiOfPbt)] / sum(gsiOfPbt[i,2:ncol(gsiOfPbt)])
}
#move group names to rownames
rownames(gsiOfPbt) <- gsiOfPbt[,1]
gsiOfPbt <- gsiOfPbt[,2:ncol(gsiOfPbt)]

# true proportion of each strata that is wild
propWild <- read.table("./inputs/smallScenario/propWildIn.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# population sizes
popSize <- read.table("./inputs/smallScenario/popSizeIn.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# tag rates
tagRates <- read.table("./inputs/smallScenario/tagRatesIn.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")


# scenarios to investigate:
## sample rate - THIS SCRIPT
## relatively similar tag rates
## highly variable tag rates
## one sub-variable, similar between wild and hatchery
## one sub-variable, distinct between wild and hatchery
## GSI composition similar between PBT groups
## GSI composition distinct between PBT groups

# sample rate
sampRate <- c(seq(.05, .10, .01), .15, .2, .25, .3, .35, .4)

#number of sims for each sample rate
numSims <- 500

# empty data structure to save results - point estimates and CIs
## for MCpbt
sr_mean <- matrix(nrow = numSims*length(sampRate), ncol = (nrow(gsiComp) + nrow(pbtComp)))
## didn't keep PBT names the same as generated by the function - woops!
allGroups <- c(gsub("PBTgroup", "pbtGroup", pbtComp$Group), gsiComp$Group)
colnames(sr_mean) <- allGroups
sr_upper <- sr_mean
sr_lower <- sr_mean
## for scobi_deux
srSD_mean <- sr_mean
srSD_upper <- sr_mean
srSD_lower <- sr_mean
srRec <- rep(0, nrow(sr_mean))
currentRow <- 1

#set seed for R
# seed for MCpbt is separate and is set in function call
set.seed(7)

# for testing
# sr=.1
# r=1
# sampRate = seq(.05, .06, .01)
# numSims = 2

for(sr in sampRate){
	print(sr)
	for(r in 1:numSims){
		print(r)
		# generate data
		trapData <- data.frame()
		for(s in 1:nrow(popSize)){
			tempData <- generatePBTGSIdata(sampRate = sr, censusSize = popSize[s,2], relSizePBTgroups = pbtComp[,(s+1)], tagRates = tagRates[,2], 
											 obsTagRates = tagRates[,2], physTagRates = rep(0,nrow(tagRates)),
					    true_clipped = 0, true_noclip_H = (1 - propWild[s,2]), true_wild = propWild[s,2], relSizeGSIgroups = gsiComp[,(s+1)], 
					    PBT_GSI_calls = gsiOfPbt, varMatList = NA)
			tempData[[1]]$StrataVar <- popSize[s,1]
			tempData[[1]]$GSI <- paste0("GSIgroup", tempData[[1]]$GSI)
			trapData <- rbind(trapData, tempData[[1]])
		}
		#get tag rate in a nice format
		tags <- tempData[[2]]
		
		#run MCpbt
		print("MCpbt")
		#using Jeffrey's prior for everything
		input <- prepStrata(trapData, tags, "GSI", "GenParentHatchery", "StrataVar", variableCols = c(), variableColsOth = c(), "AdClip",
										AI = TRUE, GSIgroups = NA,
											 variableValues = NA, variableValuesOth = NA, verbose = FALSE, symPrior = 0.5)
			
		#only one strata, so no incorporating information from other strata for pi_gsi

		aiRes <- estimStrataMCpbt(input, iter = 6000, burnIn = 1000, thin = 1, seed = 13)

		# escapement estimates for each strata
		# since these simulations don't include evaluation of estimation of population size, using the true value
		numMCMC <- nrow(aiRes[[1]]$piTot) # this gets the number of MCMC samples we took
		strataOrder <- sapply(input, function(x) return(x$strataName))
		
		escapementByStrata <- list()
		for(s in strataOrder){
			total <- popSize[popSize[,1] == s,2]
			escapementByStrata[[s]] <- rep(total, numMCMC)
		}

		escapeResults <- multByEscapement(input, aiRes, clipRes = NA, escapementByStrata, verbose = FALSE, writeSummary = FALSE)
		
		# record results - group compositions and CIs over the whole run
		colnames(escapeResults$totPiTotEstim) %in% allGroups
		tempGroups <- allGroups[allGroups %in% colnames(escapeResults$totPiTotEstim)] # incase a group wasn't sampled
		
		sr_mean[currentRow,tempGroups] <- apply(escapeResults$totPiTotEstim[,tempGroups],2,mean)
		sr_upper[currentRow,tempGroups] <- apply(escapeResults$totPiTotEstim[,tempGroups],2,quantile, .95)
		sr_lower[currentRow,tempGroups] <- apply(escapeResults$totPiTotEstim[,tempGroups],2,quantile, .05)
		
		###################################
		# run scobi_deux
		print("SD")

		#create window count input
		window <- cbind(popSize, 1:nrow(popSize))

		#run to get PBT group compositions
		SCOBI_deux_fast(adultData = trapData, windowData = window,
				 Run = "HNC_smallSR_simJP", RTYPE = "noclip_H", Hierarch_variables = c("GenParentHatchery"),
		                  SizeCut = NULL, alph = 0.1, B = 5000, writeBoot = F, pbtRates = tags,
				 adClipVariable = "AdClip", physTagsVariable = "PhysTag", pbtGroupVariable = "GenParentHatchery",
				 screenOutput = "tempScreen.txt", dataGroupVariable = "StrataVar")

		#run to get wild group compositions
		SCOBI_deux_fast(adultData = trapData, windowData = window,
				 Run = "W_smallSR_simJP", RTYPE = "wild", Hierarch_variables = c("GSI"),
		                  SizeCut = NULL, alph = 0.1, B = 5000, writeBoot = F, pbtRates = tags,
				 adClipVariable = "AdClip", physTagsVariable = "PhysTag", pbtGroupVariable = "GenParentHatchery",
				 screenOutput = "tempScreen.txt", dataGroupVariable = "StrataVar")

		#record results
		pbt_res <- read.table("./HNC_smallSR_simJP_CI_Hier_GenParentHatchery.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
		tempGroups <- allGroups[allGroups %in% pbt_res[,1]]

		srSD_mean[currentRow,tempGroups] <- pbt_res[match(tempGroups, pbt_res[,1]), 2]
		srSD_lower[currentRow,tempGroups] <- pbt_res[match(tempGroups, pbt_res[,1]), 3]
		srSD_upper[currentRow,tempGroups] <- pbt_res[match(tempGroups, pbt_res[,1]), 4]

		wild_res <- read.table("./W_smallSR_simJP_CI_Hier_GSI.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
		tempGroups <- allGroups[allGroups %in% wild_res[,1]]

		srSD_mean[currentRow,tempGroups] <- wild_res[match(tempGroups, wild_res[,1]), 2]
		srSD_lower[currentRow,tempGroups] <- wild_res[match(tempGroups, wild_res[,1]), 3]
		srSD_upper[currentRow,tempGroups] <- wild_res[match(tempGroups, wild_res[,1]), 4]
		
		srRec[currentRow] <- sr #sample rate corresponding to that row
		currentRow <- currentRow + 1
		

	}
	
}

#calculate true values
trueComp <- rep(0, ncol(sr_mean))
names(trueComp) <- colnames(sr_mean)
for(i in 2:ncol(gsiComp)){
	tot <- popSize[(i-1),2] * propWild[(i-1),2]
	tempnorm <- gsiComp[,i] / sum(gsiComp[,i])
	trueComp[gsiComp[,1]] <- trueComp[gsiComp[,1]] + (tempnorm * tot)
}
for(i in 2:ncol(pbtComp)){
	tot <- popSize[(i-1),2] * (1-propWild[(i-1),2])
	tempnorm <- pbtComp[,i] / sum(pbtComp[,i])
	tempNames <- gsub("PBTgroup", "pbtGroup", pbtComp$Group)
	trueComp[tempNames] <- trueComp[tempNames] + (tempnorm * tot)
}

#save estimates and true values
save(sr_mean, sr_upper, sr_lower, srSD_mean, srSD_upper, srSD_lower, srRec, trueComp, file = "./rdaOutputs/small_sampRate_symprior5.rda")
